# SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshSql.Conformance.Report do
  @moduledoc false
  alias AshSql.Conformance.{Adapter, Catalog, Expectations}

  def declaration_rows do
    for scenario <- Catalog.all(), adapter <- Adapter.all() do
      expectation = Expectations.for(scenario.id, adapter.id())

      %{
        scenario: scenario.id,
        area: scenario.area,
        adapter: adapter.id(),
        status: status(expectation),
        task: task(expectation),
        expected: expected(scenario),
        accepted: accepted(scenario, expectation)
      }
    end
  end

  def status(:supported), do: :supported
  def status({status, _, _}), do: status
  def task(:supported), do: nil
  def task({_, _, task}), do: task

  def outcome({:ok, actual}), do: value(actual)

  def outcome({:error, exception, message}) do
    # Stack frames contain source line numbers and function hashes, not result semantics.
    reason = message |> String.split(~r/\n\s+\([^)]+\) [^\n]*:\d+: /, parts: 2) |> hd()
    "#{inspect(exception)}: #{String.trim(reason)}"
  end

  def observation({:ok, _} = result), do: %{actual: outcome(result), details: nil}

  def observation({:error, exception, message} = result),
    do: %{actual: outcome(result), details: "#{inspect(exception)}: #{message}"}

  defp expected(%{expected: :unresolved}), do: "Semantics unresolved"
  defp expected(scenario), do: value(scenario.expected)
  defp accepted(scenario, :supported), do: expected(scenario)
  defp accepted(_, {_, {:value, actual}, _}), do: value(actual)

  defp accepted(_, {_, {:error, exception, pattern}, _}),
    do: "#{inspect(exception)} matching #{inspect(pattern)}"

  defp value(value),
    do: inspect(value, charlists: :as_lists, limit: :infinity, printable_limit: :infinity)

  def matrix do
    rows = Enum.group_by(declaration_rows(), & &1.scenario)
    adapters = Enum.map(Adapter.all(), & &1.id())

    header = """
    <!-- SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors> -->
    <!-- SPDX-License-Identifier: MIT -->

    # Aggregate expectation matrix

    Generated by `mix conformance.matrix`. These are declared contracts; `results/` contains execution results. Passing an unsupported, known-defect or unresolved expectation does not establish feature conformance.

    CI runs the base and PR suites in the same environment, compares their JSON results and shows the changes in its job summary. Elixir scenarios and expectations define the contract.

    | Scenario | #{Enum.join(adapters, " | ")} |
    | --- | #{Enum.map_join(adapters, " | ", fn _ -> "---" end)} |
    """

    body =
      Enum.map_join(Catalog.all(), "\n", fn scenario ->
        cells =
          Enum.map(adapters, fn adapter ->
            row = Enum.find(Map.fetch!(rows, scenario.id), &(&1.adapter == adapter))
            if row.task, do: "[#{row.status}](#{row.task})", else: to_string(row.status)
          end)

        source = "#{scenario.source.file}#L#{scenario.source.line}"
        "| [`#{scenario.id}`](#{source}) | #{Enum.join(cells, " | ")} |"
      end)

    header <> body <> "\n"
  end

  def console(rows) do
    rows
    |> Enum.sort_by(&{&1.scenario, &1.adapter})
    |> Enum.map_join("\n", fn row ->
      "[#{verdict(row)}] #{row.adapter} #{row.scenario} (#{row.status})\n" <>
        "  intended: #{compact(row.expected)}\n" <>
        "  observed: #{compact(row.actual)}" <>
        if(row.status == :supported, do: "", else: "\n  accepted: #{compact(row.accepted)}")
    end)
  end

  def summary(rows, comparison) do
    counts = Enum.frequencies_by(rows, &{&1.adapter, &1.status, &1.execution})

    count_rows =
      counts
      |> Enum.sort()
      |> Enum.map_join("\n", fn {{adapter, status, execution}, count} ->
        "| #{adapter} | #{status} | #{execution} | #{count} |"
      end)

    sections = [
      {"Failed checks", Enum.filter(rows, &(&1.execution == :failed)), " open"},
      {"Supported checks", Enum.filter(rows, &(&1.status == :supported)), ""},
      {"Unsupported checks", Enum.filter(rows, &(&1.status == :unsupported)), ""},
      {"Known defects", Enum.filter(rows, &(&1.status == :known_defect)), ""},
      {"Unresolved semantics", Enum.filter(rows, &(&1.status == :unresolved)), ""}
    ]

    details =
      Enum.map_join(sections, "\n", fn
        {_, [], _} ->
          ""

        {title, checks, open} ->
          "<details#{open}>\n<summary>#{title} (#{length(checks)})</summary>\n\n" <>
            results_table(checks) <> "\n</details>\n"
      end)

    """
    ## Aggregate conformance results

    Matching a recorded gap does not mean the feature is supported. Excluded or skipped checks did not run. Actual values below come from this run; the PR comparison uses JSON results from a separate base run in the same environment.

    | Adapter | Declared status | Execution | Count |
    | --- | --- | --- | ---: |
    #{count_rows}

    #{comparison}
    #{details}
    """
  end

  defp results_table(rows) do
    body =
      rows
      |> Enum.sort_by(&{&1.scenario, &1.adapter})
      |> Enum.map_join("\n", fn row ->
        "| #{code("#{row.adapter} #{row.scenario}")} | #{verdict(row)} | " <>
          "#{code(row.expected)} | #{code(row.actual)} | #{code(row.accepted)} |"
      end)

    "| Check | Result | Intended | Observed | Accepted by this test |\n" <>
      "| --- | --- | --- | --- | --- |\n" <> body <> "\n"
  end

  def verdict(%{execution: :matched, status: :supported}), do: "PASS"
  def verdict(%{execution: :matched, status: :unresolved}), do: "OBSERVATION MATCHED"
  def verdict(%{execution: :matched}), do: "GAP MATCHED"
  def verdict(%{execution: execution}), do: execution |> to_string() |> String.upcase()

  def compact(text, limit \\ 800) do
    text =
      text
      |> String.replace(~r/\e\[[0-9;]*m/, "")
      |> String.replace("\r", "\\r")
      |> String.replace("\n", "\\n")
      |> String.replace("\t", "\\t")

    if String.length(text) > limit, do: String.slice(text, 0, limit) <> " [truncated]", else: text
  end

  def code(text) do
    escaped =
      text
      |> compact(1500)
      |> String.replace("&", "&amp;")
      |> String.replace("<", "&lt;")
      |> String.replace(">", "&gt;")
      |> String.replace("|", "&#124;")
      |> String.replace("`", "&#96;")

    "<code>#{escaped}</code>"
  end

  def write_results!(rows) do
    File.mkdir_p!("results")
    name = Adapter.selected() |> Enum.map_join("-", & &1.id())
    rows = Enum.sort_by(rows, &{&1.scenario, &1.adapter})
    counts = Enum.frequencies_by(rows, &"#{&1.status}/#{&1.execution}")

    report = %{
      schema_version: 1,
      counts: counts,
      scenarios: rows,
      meaning: "A matched gap expectation is not feature conformance."
    }

    markdown = summary(rows, "")
    File.write!("results/#{name}.json", Jason.encode!(report, pretty: true) <> "\n")
    File.write!("results/#{name}.md", markdown)

    if path = summary_path(), do: File.write!(path, markdown, [:append])

    IO.puts("\n" <> console(rows))
    IO.puts("\nAggregate contracts: #{inspect(counts)}\nReport: results/#{name}.md")
  end

  def summary_path do
    case System.get_env("GITHUB_STEP_SUMMARY") do
      path when path in [nil, ""] -> nil
      path -> path
    end
  end
end
