# SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshSql.Conformance.Report do
  @moduledoc false
  alias AshSql.Conformance.{Adapter, Catalog, Expectations}

  def declaration_rows do
    for scenario <- Catalog.all(), adapter <- Adapter.all() do
      expectation = Expectations.for(scenario.id, adapter.id())

      %{
        scenario: scenario.id,
        area: scenario.area,
        adapter: adapter.id(),
        status: status(expectation),
        task: task(expectation)
      }
    end
  end

  def status(:supported), do: :supported
  def status({status, _, _}), do: status
  def task(:supported), do: nil
  def task({_, _, task}), do: task

  def matrix do
    rows = Enum.group_by(declaration_rows(), & &1.scenario)
    adapters = Enum.map(Adapter.all(), & &1.id())

    header = """
    <!-- SPDX-FileCopyrightText: 2026 ash_sql contributors <https://github.com/ash-project/ash_sql/graphs/contributors> -->
    <!-- SPDX-License-Identifier: MIT -->

    # Aggregate expectation matrix

    Generated by `mix conformance.matrix`. These are declared contracts; `results/` contains execution results. Passing an unsupported, known-defect or unresolved expectation does not establish feature conformance.

    | Scenario | #{Enum.join(adapters, " | ")} |
    | --- | #{Enum.map_join(adapters, " | ", fn _ -> "---" end)} |
    """

    body =
      Enum.map_join(Catalog.all(), "\n", fn scenario ->
        cells =
          Enum.map(adapters, fn adapter ->
            row = Enum.find(Map.fetch!(rows, scenario.id), &(&1.adapter == adapter))
            if row.task, do: "[#{row.status}](#{row.task})", else: to_string(row.status)
          end)

        "| `#{scenario.id}` | #{Enum.join(cells, " | ")} |"
      end)

    header <> body <> "\n"
  end

  def write_results!(rows) do
    File.mkdir_p!("results")
    name = Adapter.selected() |> Enum.map_join("-", & &1.id())
    rows = Enum.sort_by(rows, &{&1.scenario, &1.adapter})
    counts = Enum.frequencies_by(rows, &"#{&1.status}/#{&1.execution}")

    report = %{
      counts: counts,
      scenarios: rows,
      meaning: "A matched gap expectation is not feature conformance."
    }

    File.write!("results/#{name}.json", Jason.encode!(report, pretty: true) <> "\n")
    IO.puts("\nAggregate contracts: #{inspect(counts)}\nReport: results/#{name}.json")
  end
end

defmodule AshSql.Conformance.Formatter do
  @moduledoc false
  use GenServer
  alias AshSql.Conformance.{Expectations, Report}

  def init(_opts), do: {:ok, []}

  def handle_cast(
        {:test_finished, %{tags: %{scenario: id, adapter: adapter} = tags} = test},
        rows
      ) do
    expectation = Expectations.for(id, adapter)

    execution =
      case test.state do
        nil -> :matched
        {:excluded, _} -> :excluded
        {:skipped, _} -> :skipped
        _ -> :failed
      end

    row = %{
      scenario: id,
      adapter: adapter,
      area: tags.area,
      status: Report.status(expectation),
      task: Report.task(expectation),
      execution: execution
    }

    {:noreply, [row | rows]}
  end

  def handle_cast({:suite_finished, _times}, rows) do
    Report.write_results!(rows)
    {:noreply, rows}
  end

  def handle_cast(_event, rows), do: {:noreply, rows}
end
